[2022-06-28 23:32:45,458] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: ingest_data.get_data_to_ingest_from_local_file_task scheduled__2022-06-28T16:55:51.072773+00:00 [queued]>
[2022-06-28 23:32:45,471] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: ingest_data.get_data_to_ingest_from_local_file_task scheduled__2022-06-28T16:55:51.072773+00:00 [queued]>
[2022-06-28 23:32:45,471] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-28 23:32:45,471] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-06-28 23:32:45,471] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-28 23:32:45,509] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): get_data_to_ingest_from_local_file_task> on 2022-06-28 16:55:51.072773+00:00
[2022-06-28 23:32:45,513] {standard_task_runner.py:52} INFO - Started process 25529 to run task
[2022-06-28 23:32:45,517] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'ingest_data', 'get_data_to_ingest_from_local_file_task', 'scheduled__2022-06-28T16:55:51.072773+00:00', '--job-id', '197', '--raw', '--subdir', 'DAGS_FOLDER/CarPriceDag.py', '--cfg-path', '/tmp/tmp9kx5hubl', '--error-file', '/tmp/tmpgetl75xy']
[2022-06-28 23:32:45,518] {standard_task_runner.py:80} INFO - Job 197: Subtask get_data_to_ingest_from_local_file_task
[2022-06-28 23:32:45,552] {process_utils.py:125} INFO - Sending Signals.SIGTERM to group 25529. PIDs of all processes in the group: [25529]
[2022-06-28 23:32:45,553] {process_utils.py:80} INFO - Sending the signal Signals.SIGTERM to group 25529
[2022-06-28 23:32:45,560] {process_utils.py:75} INFO - Process psutil.Process(pid=25529, status='terminated', exitcode=<Negsignal.SIGTERM: -15>, started='23:32:44') (25529) terminated with exit code Negsignal.SIGTERM
[2022-06-28 23:32:48,229] {taskinstance.py:1149} INFO - Dependencies not met for <TaskInstance: ingest_data.get_data_to_ingest_from_local_file_task scheduled__2022-06-28T16:55:51.072773+00:00 [running]>, dependency 'Task Instance State' FAILED: Task is in the 'running' state.
[2022-06-28 23:32:48,233] {taskinstance.py:1149} INFO - Dependencies not met for <TaskInstance: ingest_data.get_data_to_ingest_from_local_file_task scheduled__2022-06-28T16:55:51.072773+00:00 [running]>, dependency 'Task Instance Not Running' FAILED: Task is in the running state
[2022-06-28 23:32:48,234] {local_task_job.py:101} INFO - Task is not able to be run
