[2022-06-28 23:49:32,813] {taskinstance.py:1149} INFO - Dependencies not met for <TaskInstance: ingest_data.get_data_to_ingest_from_local_file_task scheduled__2022-06-28T17:27:51.072773+00:00 [failed]>, dependency 'Task Instance State' FAILED: Task is in the 'failed' state.
[2022-06-28 23:49:32,822] {local_task_job.py:101} INFO - Task is not able to be run
